# Generated by Django 4.2.18 on 2025-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
